---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.owner}}-{{.Values.repo}}
spec:
  selector:
    matchLabels:
      app: {{.Values.repo}}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        timestamp: {{ default "" .Values.timestamp | quote }}
      labels:
        app: {{.Values.repo}}
        namespace: {{.Values.namespace}}
        microservice: {{.Values.repo}}
    spec:
      serviceAccountName: {{.Values.owner}}-{{.Values.repo}}
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      containers:
        - name: container-{{.Values.owner}}-{{.Values.repo}}
          image: {{ .Values.images.service.repo }}:{{ .Values.images.service.tag }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: {{.Values.resources.limits.memory}}
            requests:
              memory: {{.Values.resources.requests.memory}}
              cpu: {{.Values.resources.requests.cpu}}
          ports:
            - name: port-{{.Values.serviceport}}
              containerPort: {{.Values.serviceport}}
          env:
            {{- range $key, $val := unset .Values.env "sample_key"}}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
      imagePullSecrets:
        - name: gitsecret-{{.Values.repo}}
