---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerjsontoken }}
kind: Secret
metadata:
  name: gitsecret-{{.Values.repo}}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
type: kubernetes.io/dockerconfigjson

