---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.repo}}
spec:
  selector:
    app: {{.Values.repo}}
  type: ClusterIP
  ports:
    - name: port-{{ .Values.serviceport }}
      port: {{ .Values.serviceport }}
      targetPort: {{ .Values.serviceport }}
      protocol: TCP
