apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scalecube-robokit
    release: {{ .Release.Name | quote }}
    chart: robokit
    namespace: {{ .Values.namespace }}
  name: robokit-depl
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: scalecube-robokit
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: scalecube-robokit
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      - env:
{{- range $pkey, $pval := .Values.env }}
        - name: {{ $pkey }}
          value: {{ $pval | quote }}
{{- end }}
        image: {{ .Values.image.repository.user }}/{{ .Values.image.repository.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.env.PORT }}
          name: port-{{ .Values.env.PORT  | toString }}
          protocol: TCP
      restartPolicy: Always
