name: Robokit

on:
  push:
    paths-ignore:
      - 'charts/**'
      - '.github/workflows/**'
    branches:
      - 'develop'
      - 'master'
      - 'test'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.repository }}/robokit
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io
          platforms: linux/amd64,linux/arm64

  robokit-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo 'Robokit Deploy Trigger.'
