name: Robokit

on:
  push:
    paths-ignore:
      - 'charts/**'
      - '.github/workflows/**'
    branches:
      - 'develop'
      - 'master'

env:
  VERSION: >
    ${{ 
      inputs.version && inputs.version 
      || (github.event_name == 'push' || github.event_name == 'release') && github.ref_name 
      || (github.event_name == 'pull_request') && github.head_ref 
      || 'latest' 
    }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        run: docker login ghcr.io -u ${{ github.actor }} --password ${{ github.token }}
      - name: Build and Push Docker images
        run: |
          docker buildx build --push \
          -t ghcr.io/${{ github.repository }}/robokit:${{ env.VERSION }} \
          -t ghcr.io/${{ github.repository }}/robokit:latest \
      - name: Show Docker images
        run: docker images | grep ${{ github.repository }} || (echo Docker images not found && exit 1)
  robokit-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo 'Robokit Deploy Trigger.'
